<?php 
header('Access-Control-Allow-Origin: *');
header('Content-type: application/json');

require_once('../../config/conection.php');

$params = json_decode(file_get_contents('php://input'), TRUE);

$iniciar = curl_init();
curl_setopt($iniciar, CURLOPT_RETURNTRANSFER, true);
$dados = array(
    'cd_usuario' 		=> $params['p_cd_usuario']
);

curl_setopt($iniciar, CURLOPT_POST, true);
curl_setopt($iniciar, CURLOPT_POSTFIELDS, $dados);
curl_exec($iniciar);

$conn = oci_connect(user, pass, tns, encode);


try{

	/*$sql = "SELECT N.ID_NOTIFICACAO,
        N.TITULO,
        N.MENSAGEM,
        N.DT_NOTIFICAR,
        N.HR_NOTIFICAR,
        AL.USU_LOGIN,
        AL.RA,
        AL.NM_ALUNO,
        AL.CELULAR,
        AL.NM_RESPONSAVEL
  FROM
  BD_APLICACAO.APP_NOTIFICACAO N
  INNER JOIN (SELECT  L.USU_LOGIN, A.RA, A.NM_ALUNO, A.CODCURSO, A.TURMA AS CODTURMA, 'A' ID_PUB, A.ALU_TEL_CEL AS CELULAR, A.NM_RESPONSAVEL  FROM RM.VW_ALUNO_RESP_RM_GERAL A
              INNER JOIN BD_APLICACAO.LOGIN_APP L ON L.USU_LOGIN = A.RA AND L.USU_LOGIN = :CD_USUARIO
              UNION
              SELECT  L.USU_LOGIN, A.RA, A.NM_ALUNO, A.CODCURSO, A.TURMA AS CODTURMA, 'R' ID_PUB, A.CEL_RESPONSAVEL AS CELULAR, A.NM_RESPONSAVEL FROM RM.VW_ALUNO_RESP_RM_GERAL A
              INNER JOIN BD_APLICACAO.LOGIN_APP L ON L.USU_LOGIN = A.CPF_RESPONSAVEL AND L.USU_LOGIN = :CD_USUARIO WHERE A.CPF_RESPONSAVEL IS NOT NULL
              ) AL ON (N.ID_PUB_DESTINO = 'T' OR N.ID_PUB_DESTINO = AL.ID_PUB) 
              AND
              (
                (N.CODCURSO_DESTINO IS NULL OR N.CODCURSO_DESTINO = AL.CODCURSO) AND 
                (N.CODTURMA_DESTINO IS NULL OR N.CODTURMA_DESTINO = AL.CODTURMA)
              )
 WHERE
 N.FLG_NOTIFICAR = 'S'
 AND 
 (
     (1=1 AND  N.ID_SERVICO IN (1,3)  )
     OR
     (1=4 AND  N.ID_SERVICO=2)
 )
  AND N.ID_PUB_DESTINO IN ('A','R','T')
  AND NOT EXISTS(
      SELECT 1 FROM BD_APLICACAO.APP_NOTIFICACAO_ENVIADA E WHERE E.USU_LOGIN = AL.USU_LOGIN AND 
                E.ID_NOTIFICACAO = N.ID_NOTIFICACAO)";*/

    $sql = "SELECT N.ID_NOTIFICACAO AS ID_NOTIFICACAO,
               N.TITULO AS TITULO,
               N.MENSAGEM AS MENSAGEM,
               SUBSTR(N.ANEXO,1,255) AS DS_FOTO,
               AL.USU_LOGIN DS_FOTO_MINI,
               TRUNC(N.DT_NOTIFICAR) AS DT_NOTIFICAR,
               'INFORMAÇÃO' AS NM_TIPO,
               AL.USU_LOGIN AS CD_ALUNO,
               (SELECT  A.NM_ALUNO  FROM BD_CONTROLE.VW_ALUNO_RESP_RM A 
        JOIN BD_APLICACAO.LOGIN_APP L ON (L.USU_LOGIN = A.RA OR A.CPF_RESPONSAVEL = L.USU_LOGIN)
        AND L.USU_LOGIN =  :CD_USUARIO AND ROWNUM <= 1) AS NM_ALUNO,
               'NOTIFCACAO_APP' AS CD_EVENTO,
               TRUNC(N.DT_NOTIFICAR) AS DT_EVENTO,
               TO_CHAR(N.DT_NOTIFICAR, 'HH24:MI') AS DS_HORARIO,
               NULL AS VL_EVENTO,
               NULL AS FL_PAGO,
               'N' AS FL_LIDO,
               'S' AS FL_CONFIRMACAO     
             FROM  
             BD_APLICACAO.APP_NOTIFICACAO N 
             INNER JOIN (SELECT  L.USU_LOGIN, A.CODCURSO, A.CODTURMA, 'A' ID_PUB  FROM BD_CONTROLE.VW_ALUNO_RESP_RM A 
             INNER JOIN BD_APLICACAO.LOGIN_APP L ON L.USU_LOGIN = A.RA AND L.USU_LOGIN =  :CD_USUARIO
             UNION 
                SELECT  L.USU_LOGIN, A.CODCURSO, A.CODTURMA, 'R' ID_PUB FROM BD_CONTROLE.VW_ALUNO_RESP_RM A 
             INNER JOIN BD_APLICACAO.LOGIN_APP L ON L.USU_LOGIN = A.CPF_RESPONSAVEL AND L.USU_LOGIN =  :CD_USUARIO 
             WHERE A.CPF_RESPONSAVEL IS NOT NULL              
             
              ) AL ON
             (N.ID_PUB_DESTINO = 'T' OR N.ID_PUB_DESTINO = AL.ID_PUB) 
              AND 
             ((N.CODCURSO_DESTINO IS NULL OR N.CODCURSO_DESTINO = AL.CODCURSO) AND  (N.CODTURMA_DESTINO IS NULL OR N.CODTURMA_DESTINO = AL.CODTURMA))
 
 WHERE 
 N.FLG_NOTIFICAR = 'S'
 AND N.ID_PUB_DESTINO IN ('A','R','T')
 and N.ID_SERVICO=1
 --AND (
    --N.DT_NOTIFICAR = TRUNC(SYSDATE) AND N.HR_NOTIFICAR > = TO_CHAR(SYSDATE,'HH24:MI')   OR 
    --TRUNC(SYSDATE) - TRUNC(N.DT_NOTIFICAR) BETWEEN 0 AND 7 
 --)

  UNION 
  
SELECT N.ID_NOTIFICACAO AS ID_NOTIFICACAO,
       N.TITULO AS TITULO,
       N.MENSAGEM AS MENSAGEM,
       SUBSTR(N.ANEXO,1,255) AS DS_FOTO,
       P.USU_LOGIN DS_FOTO_MINI,
       TRUNC(N.DT_NOTIFICAR) AS DT_NOTIFICAR,
       'INFORMAÇÃO' AS NM_TIPO,
       P.USU_LOGIN AS CD_ALUNO,
       (SELECT  A.NM_ALUNO  FROM BD_CONTROLE.VW_ALUNO_RESP_RM A 
        JOIN BD_APLICACAO.LOGIN_APP L ON (L.USU_LOGIN = A.RA OR A.CPF_RESPONSAVEL = L.USU_LOGIN)
        AND L.USU_LOGIN =  :CD_USUARIO AND ROWNUM <= 1) AS NM_ALUNO,
       'NOTIFCACAO_APP' AS CD_EVENTO,
       TRUNC(N.DT_NOTIFICAR) AS DT_EVENTO,
       TO_CHAR(N.DT_NOTIFICAR, 'HH24:MI') AS DS_HORARIO,
       NULL AS VL_EVENTO,
       NULL AS FL_PAGO,
       'N' AS FL_LIDO,
       'S' AS FL_CONFIRMACAO
       
 FROM  
 BD_APLICACAO.APP_NOTIFICACAO N 
 INNER JOIN  BD_APLICACAO.APP_NOTIFICACAO_PESSOAS P ON P.ID_NOTIFICACAO = N.ID_NOTIFICACAO 
 WHERE N.ID_PUB_DESTINO IN ('E')
 and N.ID_SERVICO=1
 AND N.FLG_NOTIFICAR = 'S' AND P.USU_LOGIN =  :CD_USUARIO
 --AND (
    -- N.DT_NOTIFICAR=TRUNC(SYSDATE) AND N.HR_NOTIFICAR >= TO_CHAR(SYSDATE,'HH24:MI')   OR 
    --TRUNC(SYSDATE) - N.DT_NOTIFICAR BETWEEN 0 AND 7 
 --)

 UNION 
 
 SELECT 
       P.IDMATERIALSEC AS ID_NOTIFICACAO,
       TM.DESCRICAO AS TITULO,
       P.DESCRICAO AS MENSAGEM,
       SUBSTR(P.PATHARQUIVO,1,255) AS DS_FOTO,
       NULL AS DS_FOTO_MINI,
       P.RECCREATEDON AS DT_NOTIFICAR,
       'INFORMAÇÃO' AS NM_TIPO,
       (SELECT  L.USU_LOGIN  FROM BD_CONTROLE.VW_ALUNO_RESP_RM A 
        JOIN BD_APLICACAO.LOGIN_APP L ON (L.USU_LOGIN = A.RA OR A.CPF_RESPONSAVEL = L.USU_LOGIN)
        AND L.USU_LOGIN =  :CD_USUARIO AND ROWNUM <= 1) AS CD_ALUNO,
       (SELECT  A.NM_ALUNO  FROM BD_CONTROLE.VW_ALUNO_RESP_RM A 
        JOIN BD_APLICACAO.LOGIN_APP L ON (L.USU_LOGIN = A.RA OR A.CPF_RESPONSAVEL = L.USU_LOGIN)
        AND L.USU_LOGIN =  :CD_USUARIO AND ROWNUM <= 1) AS NM_ALUNO,
       'NOTIFCACAO_RM' AS CD_EVENTO,
       P.RECCREATEDON AS DT_EVENTO,
       TO_CHAR(P.RECCREATEDON, 'HH24:MI') AS DS_HORARIO,
       NULL AS VL_EVENTO,
       NULL AS FL_PAGO,
       'N' AS FL_LIDO,
       'S' AS FL_CONFIRMACAO
 FROM RM.SWEBMATERIALSEC P
INNER JOIN  RM.EWEBTIPOMATERIAL TM ON TM.IDTIPOMATERIAL = P.IDTIPOMATERIAL
WHERE 
EXISTS (SELECT MD.*, TD.CODTURMA FROM RM.SWEBMATERIALTURMADISC MD    
        INNER JOIN RM.STURMADISC TD ON TD.CODCOLIGADA=MD.CODCOLIGADA 
             AND TD.IDTURMADISC=MD.IDTURMADISC 
             AND TD.IDPERLET = 2
             AND TD.CODTURMA
                 IN (SELECT TURMA FROM RM.VW_ALUNO_RESP_RM_GERAL WHERE CPF_RESPONSAVEL = :CD_USUARIO)
       WHERE  MD.IDMATERIALSEC = P.IDMATERIALSEC) OR 
       NOT EXISTS (SELECT MD.*, TD.CODTURMA FROM RM.SWEBMATERIALTURMADISC MD    
                   INNER JOIN RM.STURMADISC TD ON TD.CODCOLIGADA=MD.CODCOLIGADA 
                         AND TD.IDTURMADISC=MD.IDTURMADISC 
                         AND TD.IDPERLET = 2             
       WHERE  MD.IDMATERIALSEC = P.IDMATERIALSEC)     
       
       ORDER BY DT_NOTIFICAR DESC";

    $stid   = oci_parse($conn, $sql); 

    oci_bind_by_name($stid, ':CD_USUARIO',    $dados['cd_usuario']);

    oci_execute($stid);
    oci_fetch_all($stid, $result, null, null, OCI_FETCHSTATEMENT_BY_ROW);
    echo json_encode($result);

	//echo json_encode($result);
}catch(Exception $e){
	echo 'Erro: '.$e->getMessage();
}

?>